# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ftdonor', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('beenthanked', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('groupcallout', models.CharField(max_length=100)),
                ('singleormonthly', models.CharField(choices=[('single', 'Single'), ('monthly', 'Monthly')], default='single', max_length=10)),
                ('callsign', models.CharField(choices=[('WNOC', '89.7 WNOC Toledo-Bowling Green'), ('WHRQ', '88.1 WHRQ Sandusky-Port Clinton'), ('WFOT', '89.5 WFOT Mansfield-Lexington'), ('WSHB', '90.9 WSHB Willard-Shelby'), ('WRRO', '89.9 WRRO Edon-Bryan'), ('WLBJ', '104.1 WLBJ Fostoria')], max_length=4)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('parish', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
    ]
