# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170209_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgeentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pledgeentry',
            name='callsign',
            field=models.CharField(choices=[(b'WNOC', b'89.7 WNOC Toledo-Bowling Green'), (b'WHRQ', b'88.1 WHRQ Sandusky-Port Clinton'), (b'WFOT', b'89.5 WFOT Mansfield-Lexington'), (b'WSHB', b'90.9 WSHB Willard-Shelby'), (b'WRRO', b'89.9 WRRO Edon-Bryan'), (b'WLBJ', b'104.1 WLBJ Fostoria'), (b'WEB', b'Online/WEB')], max_length=4),
        ),
    ]
