# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170917_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackathonSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
