# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trackathonsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PledgeEntry',
            new_name='Pledge',
        ),
    ]
