# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170919_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('callsign', models.CharField(max_length=4)),
            ],
        ),
    ]
