# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='beenthanked',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='ftdonor',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='groupcallout',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='singleormonthly',
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_first_time_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_thanked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Station'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
