# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170919_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
